# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'hem'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'