version: 2.1

jobs:
  deploy-to-minikube:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - run:
          name: Install kubectl
          command: |
            curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x kubectl
            mkdir -p ~/.local/bin
            mv kubectl ~/.local/bin/kubectl
            echo 'export PATH=$PATH:~/.local/bin' >> $BASH_ENV

      - run:
          name: Use host's Minikube config
          command: |
            mkdir -p ~/.kube
            echo "$KUBECONFIG_CONTENT" > ~/.kube/config

      - run:
          name: Deploy to Minikube
          command: |
            kubectl config use-context minikube
            kubectl apply -f deployment.yml

workflows:
  deploy-local:
    jobs:
      - deploy-to-minikube
