version: 2.1

jobs:
  deploy-to-minikube:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - run:
          name: Install kubectl
          command: |
            curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x kubectl
            mkdir -p ~/.local/bin
            mv kubectl ~/.local/bin/kubectl
            echo 'export PATH=$PATH:~/.local/bin' >> $BASH_ENV

      - run:
          name: Load kubeconfig from base64 and set default context
          command: |
            mkdir -p ~/.kube
            echo "$KUBECONFIG_CONTENT" | base64 -d > ~/.kube/config
            echo "Available contexts:" && kubectl config get-contexts || echo "No context info found"
            CONTEXT=$(kubectl config get-contexts -o name | head -n 1)
            if [ -n "$CONTEXT" ]; then
              echo "Setting current context to: $CONTEXT"
              kubectl config use-context "$CONTEXT"
            else
              echo "No context found in kubeconfig." && exit 1
            fi

      - run:
          name: Deploy to Kubernetes
          command: |
            kubectl apply --validate=false -f deployment.yml

workflows:
  deploy-local:
    jobs:
      - deploy-to-minikube
